#!venv/bin/python

import json
import sys

config = {
    'cropfoodRestore': 1,
    'cropsaturationRestore': 0.6,
    'snacksaturation': 0.6,
    'mealsaturation': 1.2
}

# registerItemPamCakeFood("carrotcakeitem", 5, config['mealsaturation'], BlockRegistry.carrotcake)
# registerItemPamCakeFood("holidaycakeitem", 6, config['mealsaturation'], BlockRegistry.holidaycake)
# registerItemPamCakeFood("pumpkincheesecakeitem", 6, config['mealsaturation'], BlockRegistry.pumpkincheesecake)
# registerItemPamCakeFood("pavlovaitem", 6, config['mealsaturation'], BlockRegistry.pavlovacake)
# registerItemPamCakeFood("lamingtonitem", 4, config['mealsaturation'], BlockRegistry.lamingtoncake)
# registerItemPamCakeFood("cheesecakeitem", 5, config['mealsaturation'], BlockRegistry.cheesecake)
# registerItemPamCakeFood("cherrycheesecakeitem", 6, config['mealsaturation'], BlockRegistry.cherrycheesecake)
# registerItemPamCakeFood("pineappleupsidedowncakeitem", 6, config['mealsaturation'], BlockRegistry.pineappleupsidedowncake)
# registerItemPamCakeFood("chocolatesprinklecakeitem", 8, config['mealsaturation'], BlockRegistry.chocolatesprinklecake)
# registerItemPamCakeFood("redvelvetcakeitem", 6, config['mealsaturation'], BlockRegistry.redvelvetcake)

data = {
    'items': [],
    'food': {},
}


def add_item(identifier: str):
    data['items'].append(identifier)


def add_food(identifier: str, food: int, saturation: float, speed: bool = False):
    if identifier not in data['food']:
        n_data = {
            'hunger': food,
            'saturation': saturation,
        }
        data['food'][identifier] = n_data
        return n_data
    else:
        print(f'duplicate {identifier}')
        return {}


def add_potion_food(identifier: str, food: int, saturation: float, speed: bool = False):
    add_food(identifier, food, saturation)['drink'] = True


def export():
    with open('foods.json', 'w') as output_file:
        json.dump(data, output_file, indent=2, sort_keys=True)


def move_to_ingredients(file: str):
    with open('foods.json') as data_file:
        n_data = json.load(data_file)
    with open(file) as pamhc_file:
        pamhc = json.load(pamhc_file)
    for item in map(lambda x: x[:-4], n_data['items']):
        if item in pamhc['foods']:
            pamhc['foods'].remove(item)
            pamhc['ingredients'].append(item)
            print(f'moved {item}')
    with open(file, 'w') as pamhc_file:
        json.dump(pamhc, pamhc_file, sort_keys=True, indent=2)


def do_foods():
    add_item("garliccoinitem")
    add_food("ediblerootitem", config['cropfoodRestore'], config['cropsaturationRestore'])
    add_food("sunflowerseedsitem", config['cropfoodRestore'], config['cropsaturationRestore'])
    add_food("calamarirawitem", 1, config['snacksaturation'])
    add_food("calamaricookeditem", 2, config['mealsaturation'])
    add_item("saltitem")
    add_item("wovencottonitem")
    add_item("freshwateritem")
    add_item("freshmilkitem")
    add_food("grilledasparagusitem", 2, config['mealsaturation'])
    add_food("bakedsweetpotatoitem", 2, config['mealsaturation'])
    add_food("grilledeggplantitem", 2, config['mealsaturation'])
    add_food("toastitem", 4, config['mealsaturation'])
    add_food("cheeseitem", 2, config['mealsaturation'])
    add_food("icecreamitem", 3, config['mealsaturation'])
    add_food("grilledcheeseitem", 8, config['mealsaturation'])
    add_food("applesauceitem", 2, config['mealsaturation'])
    add_food("pumpkinbreaditem", 5, config['mealsaturation'])
    add_food("caramelappleitem", 3, config['mealsaturation'])    
    add_food("applepieitem", 5, config['mealsaturation'])    
    add_potion_food("teaitem", 2, config['mealsaturation'])
    add_potion_food("coffeeitem", 2, config['mealsaturation'])
    add_food("popcornitem", 2, config['mealsaturation'])
    add_food("raisinsitem", 2, config['mealsaturation'])
    add_food("ricecakeitem", 2, config['mealsaturation'])
    add_food("toastedcoconutitem", 2, config['mealsaturation'])
    add_food("roastedpumpkinseedsitem", 1, config['mealsaturation'])    
    add_item("vanillaitem")
    add_item("toastedsesameseedsitem")
    add_item("flouritem")    
    add_item("doughitem")    
    add_item("pastaitem")
    add_item("heavycreamitem")
    add_item("butteritem")
    add_food("pumpkinsoupitem", 4, config['mealsaturation'])
    add_potion_food("melonsmoothieitem", 3, config['mealsaturation'])    
    add_food("carrotsoupitem", 4, config['mealsaturation'])
    add_food("glazedcarrotsitem", 4, config['mealsaturation'])
    add_food("butteredpotatoitem", 4, config['mealsaturation'])
    add_food("loadedbakedpotatoitem", 8, config['mealsaturation'])
    add_food("mashedpotatoesitem", 5, config['mealsaturation'])
    add_food("potatosaladitem", 3, config['mealsaturation'])
    add_food("potatosoupitem", 4, config['mealsaturation'])
    add_food("friesitem", 2, config['mealsaturation'])
    add_food("grilledmushroomitem", 2, config['mealsaturation'])
    add_food("stuffedmushroomitem", 7, config['mealsaturation'])
    add_food("chickensandwichitem", 6, config['mealsaturation'])
    add_food("chickennoodlesoupitem", 6, config['mealsaturation'])
    add_food("chickenpotpieitem", 7, config['mealsaturation'])
    add_food("breadedporkchopitem", 5, config['mealsaturation'])
    add_food("hotdogitem", 5, config['mealsaturation'])
    add_food("bakedhamitem", 4, config['mealsaturation'])
    add_food("hamburgeritem", 6, config['mealsaturation'])
    add_food("cheeseburgeritem", 8, config['mealsaturation'])    
    add_food("potroastitem", 6, config['mealsaturation'])
    add_food("fishsandwichitem", 6, config['mealsaturation'])
    add_food("fishsticksitem", 5, config['mealsaturation'])
    add_food("fishandchipsitem", 7, config['mealsaturation'])
    add_item("mayoitem")
    add_food("friedeggitem", 3, config['mealsaturation'])
    add_food("scrambledeggitem", 3, config['mealsaturation'])
    add_food("boiledeggitem", 3, config['mealsaturation'])
    add_food("eggsaladitem", 4, config['mealsaturation'])    
    add_food("caramelitem", 1, config['mealsaturation'])
    add_food("taffyitem", 2, config['mealsaturation'])
    add_food("spidereyesoupitem", 4, config['mealsaturation'])
    add_food("zombiejerkyitem", 3, config['mealsaturation'])
    add_item("cocoapowderitem")
    add_food("chocolatebaritem", 1, config['mealsaturation'])
    add_potion_food("hotchocolateitem", 2, config['mealsaturation'])
    add_food("chocolateicecreamitem", 4, config['mealsaturation'])
    add_food("vegetablesoupitem", 5, config['mealsaturation'])
    add_food("stockitem", 2, config['mealsaturation'])
    add_food("fruitsaladitem", 2, config['mealsaturation'])
    add_food("spagettiitem", 3, config['mealsaturation'])
    add_food("spagettiandmeatballsitem", 5, config['mealsaturation'])
    add_food("tomatosoupitem", 3, config['mealsaturation'])
    add_item("ketchupitem")
    add_food("chickenparmasanitem", 5, config['mealsaturation'])    
    add_food("springsaladitem", 2, config['mealsaturation'])
    add_food("porklettucewrapitem", 3, config['mealsaturation'])
    add_food("fishlettucewrapitem", 3, config['mealsaturation'])
    add_food("bltitem", 8, config['mealsaturation'])    
    add_food("leafychickensandwichitem", 7, config['mealsaturation'])
    add_food("leafyfishsandwichitem", 7, config['mealsaturation'])    
    
    add_food("potatocakesitem", 4, config['mealsaturation'])
    add_food("hashitem", 5, config['mealsaturation'])
    add_food("braisedonionsitem", 5, config['mealsaturation'])    
    add_food("cornonthecobitem", 3, config['mealsaturation'])
    add_item("cornmealitem")
    add_food("cornbreaditem", 4, config['mealsaturation'])
    add_food("tortillaitem", 3, config['mealsaturation'])
    add_food("nachoesitem", 5, config['mealsaturation'])
    add_food("tacoitem", 8, config['mealsaturation'])
    add_food("fishtacoitem", 8, config['mealsaturation'])
    add_food("creamedcornitem", 3, config['mealsaturation'])
    add_food("strawberrysmoothieitem", 3, config['mealsaturation'])
    add_food("strawberrypieitem", 5, config['mealsaturation'])
    add_food("strawberrysaladitem", 3, config['mealsaturation'])
    add_food("chocolatestrawberryitem", 2, config['mealsaturation'])
    add_food("peanutbutteritem", 1, config['mealsaturation'])
    add_food("trailmixitem", 4, config['mealsaturation'])
    add_food("pbandjitem", 6, config['mealsaturation'])
    add_food("peanutbuttercookiesitem", 5, config['mealsaturation'])
    add_item("vinegaritem")
    add_food("grapejellyitem", 2, config['mealsaturation'])
    add_food("grapesaladitem", 3, config['mealsaturation'])
    add_food("raisincookiesitem", 6, config['mealsaturation'])
    add_food("picklesitem", 4, config['mealsaturation'])
    add_food("cucumbersaladitem", 3, config['mealsaturation'])
    add_food("cucumbersoupitem", 4, config['mealsaturation'])
    add_food("vegetarianlettucewrapitem", 3, config['mealsaturation'])
    add_food("marinatedcucumbersitem", 5, config['mealsaturation'])
    add_food("ricesoupitem", 3, config['mealsaturation'])
    add_food("friedriceitem", 5, config['mealsaturation'])
    add_food("mushroomrisottoitem", 5, config['mealsaturation'])
    add_food("curryitem", 6, config['mealsaturation'])    
    add_food("rainbowcurryitem", 7, config['mealsaturation'])
    add_food("refriedbeansitem", 4, config['mealsaturation'])
    add_food("bakedbeansitem", 4, config['mealsaturation'])
    add_food("beansandriceitem", 5, config['mealsaturation'])
    add_food("chiliitem", 4, config['mealsaturation'])
    add_food("beanburritoitem", 7, config['mealsaturation'])
    add_food("stuffedpepperitem", 3, config['mealsaturation'])
    add_food("veggiestirfryitem", 5, config['mealsaturation'])
    add_food("grilledskewersitem", 4, config['mealsaturation'])    
    add_food("omeletitem", 4, config['mealsaturation'])
    add_food("hotwingsitem", 3, config['mealsaturation'])
    add_food("chilipoppersitem", 6, config['mealsaturation'])
    add_food("extremechiliitem", 5, config['mealsaturation'])
    add_food("chilichocolateitem", 2, config['mealsaturation'])
    add_potion_food("lemonaideitem", 3, config['mealsaturation'])
    add_food("lemonbaritem", 5, config['mealsaturation'])
    add_food("fishdinneritem", 7, config['mealsaturation'])
    add_food("lemonsmoothieitem", 3, config['mealsaturation'])
    add_food("lemonmeringueitem", 6, config['mealsaturation'])
    add_food("candiedlemonitem", 2, config['mealsaturation'])
    add_food("lemonchickenitem", 5, config['mealsaturation'])
    add_potion_food("blueberrysmoothieitem", 3, config['mealsaturation'])
    add_food("blueberrypieitem", 5, config['mealsaturation'])
    add_food("blueberrymuffinitem", 4, config['mealsaturation'])
    add_food("pancakesitem", 4, config['mealsaturation'])
    add_food("blueberrypancakesitem", 7, config['mealsaturation'])
    add_food("cherrypieitem", 5, config['mealsaturation'])
    add_food("chocolatecherryitem", 2, config['mealsaturation'])
    add_potion_food("cherrysmoothieitem", 3, config['mealsaturation'])    
    add_food("stuffedeggplantitem", 7, config['mealsaturation'])
    add_food("eggplantparmitem", 5, config['mealsaturation'])
    add_potion_food("raspberryicedteaitem", 3, config['mealsaturation'])
    add_potion_food("chaiteaitem", 3, config['mealsaturation'])
    add_potion_food("espressoitem", 4, config['mealsaturation'])
    add_potion_food("coffeeconlecheitem", 6, config['mealsaturation'])
    add_food("mochaicecreamitem", 5, config['mealsaturation'])
    add_food("pickledbeetsitem", 4, config['mealsaturation'])
    add_food("beetsaladitem", 6, config['mealsaturation'])
    add_food("beetsoupitem", 4, config['mealsaturation'])
    add_food("bakedbeetsitem", 4, config['mealsaturation'])
    add_food("broccolimacitem", 4, config['mealsaturation'])
    add_food("broccolindipitem", 3, config['mealsaturation'])
    add_food("creamedbroccolisoupitem", 6, config['mealsaturation'])
    add_food("sweetpotatopieitem", 9, config['mealsaturation'])
    add_food("candiedsweetpotatoesitem", 3, config['mealsaturation'])
    add_food("mashedsweetpotatoesitem", 3, config['mealsaturation'])
    add_food("steamedpeasitem", 2, config['mealsaturation'])
    add_food("splitpeasoupitem", 6, config['mealsaturation'])    
    add_food("pineapplehamitem", 5, config['mealsaturation'])
    add_food("pineappleyogurtitem", 2, config['mealsaturation'])
    add_food("turnipsoupitem", 6, config['mealsaturation'])
    add_food("roastedrootveggiemedleyitem", 4, config['mealsaturation'])
    add_food("bakedturnipsitem", 5, config['mealsaturation'])
    add_food("gingerbreaditem", 7, config['mealsaturation'])
    add_food("gingersnapsitem", 3, config['mealsaturation'])
    add_food("candiedgingeritem", 2, config['mealsaturation'])
    add_item("mustarditem")
    add_food("softpretzelandmustarditem", 7, config['mealsaturation'])
    add_food("spicymustardporkitem", 4, config['mealsaturation'])
    add_food("spicygreensitem", 5, config['mealsaturation'])
    add_food("garlicbreaditem", 7, config['mealsaturation'])
    add_food("garlicmashedpotatoesitem", 6, config['mealsaturation'])
    add_food("garlicchickenitem", 6, config['mealsaturation'])
    add_food("summerradishsaladitem", 5, config['mealsaturation'])
    add_food("summersquashwithradishitem", 5, config['mealsaturation'])
    add_food("celeryandpeanutbutteritem", 2, config['mealsaturation'])
    add_food("chickencelerycasseroleitem", 6, config['mealsaturation'])
    add_food("peasandceleryitem", 4, config['mealsaturation'])
    add_food("celerysoupitem", 5, config['mealsaturation'])
    add_food("zucchinibreaditem", 6, config['mealsaturation'])
    add_food("zucchinifriesitem", 9, config['mealsaturation'])
    add_food("zestyzucchiniitem", 6, config['mealsaturation'])
    add_food("zucchinibakeitem", 9, config['mealsaturation'])
    add_food("asparagusquicheitem", 6, config['mealsaturation'])
    add_food("asparagussoupitem", 6, config['mealsaturation'])
    add_food("walnutraisinbreaditem", 7, config['mealsaturation'])
    add_food("candiedwalnutsitem", 4, config['mealsaturation'])
    add_food("brownieitem", 8, config['mealsaturation'])
    add_potion_food("papayasmoothieitem", 3, config['mealsaturation'])
    add_food("papayayogurtitem", 2, config['mealsaturation'])
    add_potion_food("starfruitsmoothieitem", 3, config['mealsaturation'])
    add_food("starfruityogurtitem", 2, config['mealsaturation'])
    add_food("guacamoleitem", 5, config['mealsaturation'])
    add_food("creamofavocadosoupitem", 6, config['mealsaturation'])
    add_food("avocadoburritoitem", 8, config['mealsaturation'])
    add_food("poachedpearitem", 3, config['mealsaturation'])
    add_food("fruitcrumbleitem", 5, config['mealsaturation'])
    add_food("pearyogurtitem", 2, config['mealsaturation'])
    add_food("plumyogurtitem", 2, config['mealsaturation'])
    add_food("bananasplititem", 7, config['mealsaturation'])
    add_food("banananutbreaditem", 5, config['mealsaturation'])
    add_potion_food("bananasmoothieitem", 3, config['mealsaturation'])
    add_food("bananayogurtitem", 2, config['mealsaturation'])
    add_potion_food("coconutmilkitem", 1, config['mealsaturation'])
    add_food("chickencurryitem", 9, config['mealsaturation'])
    add_food("coconutshrimpitem", 7, config['mealsaturation'])
    add_food("coconutyogurtitem", 2, config['mealsaturation'])
    add_food("orangechickenitem", 6, config['mealsaturation'])
    add_potion_food("orangesmoothieitem", 3, config['mealsaturation'])
    add_food("orangeyogurtitem", 2, config['mealsaturation'])
    add_food("peachcobbleritem", 5, config['mealsaturation'])
    add_food("peachsmoothieitem", 3, config['mealsaturation'])
    add_food("peachyogurtitem", 2, config['mealsaturation'])
    add_food("keylimepieitem", 6, config['mealsaturation'])
    add_potion_food("limesmoothieitem", 3, config['mealsaturation'])
    add_food("limeyogurtitem", 2, config['mealsaturation'])
    add_potion_food("mangosmoothieitem", 3, config['mealsaturation'])
    add_food("mangoyogurtitem", 2, config['mealsaturation'])
    add_potion_food("pomegranatesmoothieitem", 3, config['mealsaturation'])
    add_food("pomegranateyogurtitem", 2, config['mealsaturation'])
    add_food("vanillayogurtitem", 2, config['mealsaturation'])
    add_food("cinnamonrollitem", 5, config['mealsaturation'])
    add_food("frenchtoastitem", 8, config['mealsaturation'])
    add_food("marshmellowsitem", 4, config['mealsaturation'])
    add_food("donutitem", 4, config['mealsaturation'])
    add_food("chocolatedonutitem", 5, config['mealsaturation'])
    add_food("powdereddonutitem", 5, config['mealsaturation'])
    add_food("jellydonutitem", 6, config['mealsaturation'])
    add_food("frosteddonutitem", 8, config['mealsaturation'])
    add_food("cactussoupitem", 3, config['mealsaturation'])
    add_food("wafflesitem", 6, config['mealsaturation'])
    add_food("seedsoupitem", 3, config['mealsaturation'])
    add_food("softpretzelitem", 6, config['mealsaturation'])
    add_food("jellybeansitem", 3, config['mealsaturation'])
    add_food("biscuititem", 5, config['mealsaturation'])
    add_food("creamcookieitem", 6, config['mealsaturation'])
    add_food("jaffaitem", 6, config['mealsaturation'])
    add_food("friedchickenitem", 8, config['mealsaturation'])    
    add_food("footlongitem", 8, config['mealsaturation'])
    add_food("blueberryyogurtitem", 2, config['mealsaturation'])
    add_food("lemonyogurtitem", 2, config['mealsaturation'])
    add_food("cherryyogurtitem", 2, config['mealsaturation'])
    add_food("strawberryyogurtitem", 2, config['mealsaturation'])
    add_food("grapeyogurtitem", 2, config['mealsaturation'])
    add_food("chocolateyogurtitem", 2, config['mealsaturation'])
    add_food("blackberrycobbleritem", 5, config['mealsaturation'])
    add_potion_food("blackberrysmoothieitem", 3, config['mealsaturation'])
    add_food("blackberryyogurtitem", 2, config['mealsaturation'])
    add_potion_food("chocolatemilkitem", 2, config['mealsaturation'])
    add_food("pumpkinyogurtitem", 2, config['mealsaturation'])
    add_food("raspberrypieitem", 5, config['mealsaturation'])
    add_potion_food("raspberrysmoothieitem", 3, config['mealsaturation'])
    add_food("raspberryyogurtitem", 2, config['mealsaturation'])
    add_food("cinnamonsugardonutitem", 7, config['mealsaturation'])
    add_food("melonyogurtitem", 2, config['mealsaturation'])
    add_potion_food("kiwismoothieitem", 3, config['mealsaturation'])
    add_food("kiwiyogurtitem", 2, config['mealsaturation'])
    add_food("plainyogurtitem", 1, config['mealsaturation'])
    add_food("appleyogurtitem", 2, config['mealsaturation'])
    add_food("saltedsunflowerseedsitem", 2, config['mealsaturation'])
    add_food("sunflowerwheatrollsitem", 6, config['mealsaturation'])
    add_food("sunflowerbroccolisaladitem", 6, config['mealsaturation'])
    add_food("cranberrysauceitem", 2, config['mealsaturation'])
    add_food("cranberrybaritem", 5, config['mealsaturation'])
    add_food("peppermintitem", 2, config['mealsaturation'])
    add_item("blackpepperitem")
    add_item("groundcinnamonitem")
    add_item("groundnutmegitem")
    add_item("oliveoilitem")
    add_food("baklavaitem", 8, config['mealsaturation'])
    add_food("gummybearsitem", 3, config['mealsaturation'])    
    add_potion_food("fruitpunchitem", 2, config['mealsaturation'])
    add_food("meatystewitem", 5, config['mealsaturation'])
    add_food("mixedsaladitem", 6, config['mealsaturation'])
    add_food("pinacoladaitem", 2, config['mealsaturation'])
    add_item("saladdressingitem")
    add_food("shepardspieitem", 8, config['mealsaturation'])
    add_potion_food("eggnogitem", 5, config['mealsaturation'])
    add_food("custarditem", 5, config['mealsaturation'])
    add_food("sushiitem", 4, config['mealsaturation'])
    add_food("gardensoupitem", 4, config['mealsaturation'])
    add_food("applejellyitem", 2, config['mealsaturation'])
    add_food("applejellysandwichitem", 6, config['mealsaturation'])
    add_food("blackberryjellyitem", 2, config['mealsaturation'])
    add_food("blackberryjellysandwichitem", 6, config['mealsaturation'])
    add_food("blueberryjellyitem", 2, config['mealsaturation'])
    add_food("blueberryjellysandwichitem", 6, config['mealsaturation'])
    add_food("cherryjellyitem", 2, config['mealsaturation'])
    add_food("cherryjellysandwichitem", 6, config['mealsaturation'])
    add_food("cranberryjellyitem", 2, config['mealsaturation'])
    add_food("cranberryjellysandwichitem", 6, config['mealsaturation'])
    add_food("kiwijellyitem", 2, config['mealsaturation'])
    add_food("kiwijellysandwichitem", 6, config['mealsaturation'])
    add_food("lemonjellyitem", 2, config['mealsaturation'])
    add_food("lemonjellysandwichitem", 6, config['mealsaturation'])
    add_food("limejellyitem", 2, config['mealsaturation'])
    add_food("limejellysandwichitem", 6, config['mealsaturation'])
    add_food("mangojellyitem", 2, config['mealsaturation'])
    add_food("mangojellysandwichitem", 6, config['mealsaturation'])
    add_food("orangejellyitem", 2, config['mealsaturation'])
    add_food("orangejellysandwichitem", 6, config['mealsaturation'])
    add_food("papayajellyitem", 2, config['mealsaturation'])
    add_food("papayajellysandwichitem", 6, config['mealsaturation'])
    add_food("peachjellyitem", 2, config['mealsaturation'])
    add_food("peachjellysandwichitem", 6, config['mealsaturation'])
    add_food("pomegranatejellyitem", 2, config['mealsaturation'])
    add_food("pomegranatejellysandwichitem", 6, config['mealsaturation'])
    add_food("raspberryjellyitem", 2, config['mealsaturation'])
    add_food("raspberryjellysandwichitem", 6, config['mealsaturation'])
    add_food("starfruitjellyitem", 2, config['mealsaturation'])
    add_food("starfruitjellysandwichitem", 6, config['mealsaturation'])
    add_food("strawberryjellyitem", 2, config['mealsaturation'])
    add_food("strawberryjellysandwichitem", 6, config['mealsaturation'])
    add_food("watermelonjellyitem", 2, config['mealsaturation'])
    add_food("watermelonjellysandwichitem", 6, config['mealsaturation'])
    add_item("bubblywateritem")
    add_potion_food("cherrysodaitem", 3, config['mealsaturation'])
    add_potion_food("colasodaitem", 3, config['mealsaturation'])
    add_potion_food("gingersodaitem", 3, config['mealsaturation'])
    add_potion_food("grapesodaitem", 4, config['mealsaturation'])
    add_potion_food("lemonlimesodaitem", 5, config['mealsaturation'])
    add_potion_food("orangesodaitem", 4, config['mealsaturation'])
    add_potion_food("rootbeersodaitem", 3, config['mealsaturation'])
    add_potion_food("strawberrysodaitem", 4, config['mealsaturation'])
    add_food("caramelicecreamitem", 4, config['mealsaturation'])
    add_food("mintchocolatechipicecreamitem", 5, config['mealsaturation'])
    add_food("strawberryicecreamitem", 4, config['mealsaturation'])
    add_food("vanillaicecreamitem", 4, config['mealsaturation'])
    add_food("gingerchickenitem", 6, config['mealsaturation'])
    add_food("oldworldveggiesoupitem", 5, config['mealsaturation'])
    add_food("spicebunitem", 6, config['mealsaturation'])
    add_food("gingeredrhubarbtartitem", 8, config['mealsaturation'])
    add_food("lambbarleysoupitem", 7, config['mealsaturation'])
    add_food("honeylemonlambitem", 6, config['mealsaturation'])
    add_food("pumpkinoatsconesitem", 5, config['mealsaturation'])
    add_food("beefjerkyitem", 3, config['mealsaturation'])
    add_food("ovenroastedcaulifloweritem", 4, config['mealsaturation'])
    add_food("leekbaconsoupitem", 5, config['mealsaturation'])
    add_food("herbbutterparsnipsitem", 4, config['mealsaturation'])
    add_food("scallionbakedpotatoitem", 4, config['mealsaturation'])
    add_potion_food("soymilkitem", 1, config['mealsaturation'])
    add_food("firmtofuitem", 2, config['mealsaturation'])
    add_food("silkentofuitem", 1, config['mealsaturation'])
    add_food("bamboosteamedriceitem", 2, config['mealsaturation'])
    add_food("roastedchestnutitem", 2, config['mealsaturation'])
    add_food("sweetpotatosouffleitem", 7, config['mealsaturation'])
    add_food("cashewchickenitem", 5, config['mealsaturation'])
    add_food("apricotyogurtitem", 2, config['mealsaturation'])
    add_food("apricotglazedporkitem", 4, config['mealsaturation'])
    add_food("apricotjellyitem", 2, config['mealsaturation'])
    add_food("apricotjellysandwichitem", 6, config['mealsaturation'])
    add_potion_food("apricotsmoothieitem", 3, config['mealsaturation'])
    add_food("figbaritem", 5, config['mealsaturation'])
    add_food("figjellyitem", 2, config['mealsaturation'])
    add_food("figjellysandwichitem", 6, config['mealsaturation'])
    add_potion_food("figsmoothieitem", 3, config['mealsaturation'])
    add_food("figyogurtitem", 2, config['mealsaturation'])
    add_food("grapefruitjellyitem", 2, config['mealsaturation'])
    add_food("grapefruitjellysandwichitem", 6, config['mealsaturation'])
    add_potion_food("grapefruitsmoothieitem", 3, config['mealsaturation'])
    add_food("grapefruityogurtitem", 2, config['mealsaturation'])
    add_potion_food("grapefruitsodaitem", 4, config['mealsaturation'], True)
    add_food("citrussaladitem", 2, config['mealsaturation'])
    add_food("pecanpieitem", 7, config['mealsaturation'])
    add_food("pralinesitem", 2, config['mealsaturation'])
    add_food("persimmonyogurtitem", 2, config['mealsaturation'])
    add_potion_food("persimmonsmoothieitem", 3, config['mealsaturation'])
    add_food("persimmonjellyitem", 2, config['mealsaturation'])
    add_food("persimmonjellysandwichitem", 6, config['mealsaturation'])
    add_food("pistachiobakedsalmonitem", 3, config['mealsaturation'])
    add_food("baconwrappeddatesitem", 3, config['mealsaturation'])
    add_food("datenutbreaditem", 5, config['mealsaturation'])
    add_food("maplesyruppancakesitem", 7, config['mealsaturation'])
    add_food("maplesyrupwafflesitem", 7, config['mealsaturation'])
    add_food("maplesausageitem", 4, config['mealsaturation'])
    add_food("mapleoatmealitem", 2, config['mealsaturation'])
    add_food("peachesandcreamoatmealitem", 3, config['mealsaturation'])
    add_food("cinnamonappleoatmealitem", 3, config['mealsaturation'])
    add_food("maplecandiedbaconitem", 3, config['mealsaturation'])
    add_food("toastsandwichitem", 9, config['mealsaturation'])
    add_food("potatoandcheesepirogiitem", 6, config['mealsaturation'])
    add_food("zeppoleitem", 5, config['mealsaturation'])
    add_food("sausageinbreaditem", 9, config['mealsaturation'])
    add_food("chocolatecaramelfudgeitem", 2, config['mealsaturation'])
    add_food("lavendershortbreaditem", 4, config['mealsaturation'])
    add_food("beefwellingtonitem", 7, config['mealsaturation'])
    add_food("epicbaconitem", 9, config['mealsaturation'])
    add_food("manjuuitem", 3, config['mealsaturation'])
    add_food("chickengumboitem", 9, config['mealsaturation'])
    add_food("generaltsochickenitem", 7, config['mealsaturation'])
    add_food("californiarollitem", 6, config['mealsaturation'])
    add_food("futomakiitem", 9, config['mealsaturation'])    
    add_food("vegemiteitem", 4, config['mealsaturation'])
    add_food("honeycombchocolatebaritem", 3, config['mealsaturation'])
    add_food("cherrycoconutchocolatebaritem", 4, config['mealsaturation'])
    add_food("fairybreaditem", 8, config['mealsaturation'])    
    add_food("timtamitem", 4, config['mealsaturation'])    

    add_food("damperitem", 5, config['mealsaturation'])    

    add_food("gherkinitem", 5, config['mealsaturation'])    
    add_food("ceasarsaladitem", 9, config['mealsaturation'])
    add_food("chaoscookieitem", 3, config['mealsaturation'])
    add_food("chocolatebaconitem", 3, config['mealsaturation'])
    add_food("lambkebabitem", 5, config['mealsaturation'])
    add_food("nutellaitem", 2, config['mealsaturation'])
    add_food("snickersbaritem", 3, config['mealsaturation'])    
    add_food("steamedspinachitem", 2, config['mealsaturation'])
    add_food("vegemiteontoastitem", 5, config['mealsaturation'])    

    add_food("clamcookeditem", 2, config['mealsaturation'])
    add_food("crabcookeditem", 2, config['mealsaturation'])
    add_food("crayfishcookeditem", 2, config['mealsaturation'])
    add_food("frogcookeditem", 2, config['mealsaturation'])
    add_food("octopuscookeditem", 2, config['mealsaturation'])
    add_food("scallopcookeditem", 2, config['mealsaturation'])
    add_food("shrimpcookeditem", 2, config['mealsaturation'])
    add_food("snailcookeditem", 2, config['mealsaturation'])
    add_food("turtlecookeditem", 2, config['mealsaturation'])
    add_food("oystercookeditem", 2, config['mealsaturation'])    
    add_food("applecideritem", 2, config['mealsaturation'])
    add_food("bangersandmashitem", 9, config['mealsaturation'])
    add_food("batteredsausageitem", 7, config['mealsaturation'])
    add_item("batteritem")
    add_food("chorizoitem", 5, config['mealsaturation'])
    add_food("coleslawitem", 4, config['mealsaturation'])
    add_potion_food("energydrinkitem", 5, config['mealsaturation'], True)
    add_food("friedonionsitem", 2, config['mealsaturation'])    
    add_food("mincepieitem", 9, config['mealsaturation'])
    add_food("onionhamburgeritem", 8, config['mealsaturation'])
    add_food("pepperoniitem", 5, config['mealsaturation'])
    add_food("pickledonionsitem", 4, config['mealsaturation'])
    add_food("porksausageitem", 4, config['mealsaturation'])
    add_food("raspberrytrifleitem", 6, config['mealsaturation'])    
    add_food("pumpkinmuffinitem", 4, config['mealsaturation'])
    add_food("suaderoitem", 3, config['mealsaturation'])    
    add_food("turkeyrawitem", 1, config['mealsaturation'])
    add_food("turkeycookeditem", 2, config['mealsaturation'])
    add_food("venisonrawitem", 1, config['mealsaturation'])
    add_food("venisoncookeditem", 2, config['mealsaturation'])
    add_food("strawberrymilkshakeitem", 3, config['mealsaturation'])
    add_food("chocolatemilkshakeitem", 3, config['mealsaturation'])
    add_food("bananamilkshakeitem", 3, config['mealsaturation'])
    add_food("cornflakesitem", 2, config['mealsaturation'])    
    add_food("roastchickenitem", 4, config['mealsaturation'])
    add_food("roastpotatoesitem", 3, config['mealsaturation'])
    add_food("sundayroastitem", 8, config['mealsaturation'])
    add_food("bbqpulledporkitem", 8, config['mealsaturation'])
    add_food("lambwithmintsauceitem", 6, config['mealsaturation'])
    add_food("steakandchipsitem", 4, config['mealsaturation'])
    add_food("cherryicecreamitem", 4, config['mealsaturation'])
    add_food("pistachioicecreamitem", 4, config['mealsaturation'])
    add_food("neapolitanicecreamitem", 4, config['mealsaturation'])
    add_food("spumoniicecreamitem", 4, config['mealsaturation'])
    add_food("almondbutteritem", 1, config['mealsaturation'])
    add_food("cashewbutteritem", 1, config['mealsaturation'])
    add_food("chestnutbutteritem", 1, config['mealsaturation'])
    add_food("cornishpastyitem", 8, config['mealsaturation'])
    add_food("cottagepieitem", 8, config['mealsaturation'])
    add_food("croissantitem", 6, config['mealsaturation'])
    add_item("currypowderitem")
    add_food("dimsumitem", 8, config['mealsaturation'])
    add_food("friedpecanokraitem", 4, config['mealsaturation'])
    add_food("gooseberryjellyitem", 2, config['mealsaturation'])
    add_food("gooseberryjellysandwichitem", 6, config['mealsaturation'])
    add_food("gooseberrymilkshakeitem", 3, config['mealsaturation'])
    add_food("gooseberrypieitem", 5, config['mealsaturation'])
    add_food("gooseberrysmoothieitem", 3, config['mealsaturation'])
    add_food("gooseberryyogurtitem", 2, config['mealsaturation'])    
    add_food("hushpuppiesitem", 5, config['mealsaturation'])
    add_food("kimchiitem", 5, config['mealsaturation'])
    add_food("mochiitem", 3, config['mealsaturation'])
    add_food("museliitem", 6, config['mealsaturation'])    
    add_food("naanitem", 5, config['mealsaturation'])
    add_food("okrachipsitem", 3, config['mealsaturation'])
    add_food("okracreoleitem", 6, config['mealsaturation'])
    add_food("pistachiobutteritem", 1, config['mealsaturation'])    
    add_food("porklomeinitem", 9, config['mealsaturation'])
    add_food("salmonpattiesitem", 9, config['mealsaturation'])
    add_food("sausageitem", 4, config['mealsaturation'])
    add_food("sausagerollitem", 9, config['mealsaturation'])
    add_food("sesameballitem", 5, config['mealsaturation'])
    add_food("sesamesnapsitem", 2, config['mealsaturation'])
    add_food("shrimpokrahushpuppiesitem", 8, config['mealsaturation'])
    add_item("soysauceitem")
    add_food("sweetpickleitem", 6, config['mealsaturation'])
    add_food("veggiestripsitem", 5, config['mealsaturation'])
    add_food("vindalooitem", 7, config['mealsaturation'])
    add_food("applesmoothieitem", 3, config['mealsaturation'])
    add_food("coconutsmoothieitem", 3, config['mealsaturation'])
    add_food("cranberrysmoothieitem", 3, config['mealsaturation'])
    add_food("cranberryyogurtitem", 2, config['mealsaturation'])
    add_food("grapesmoothieitem", 3, config['mealsaturation'])
    add_food("pearsmoothieitem", 3, config['mealsaturation'])
    add_food("pearjellyitem", 2, config['mealsaturation'])
    add_food("pearjellysandwichitem", 6, config['mealsaturation'])
    add_food("plumsmoothieitem", 3, config['mealsaturation'])
    add_food("plumjellyitem", 2, config['mealsaturation'])
    add_food("plumjellysandwichitem", 6, config['mealsaturation'])
    add_food("honeysandwichitem", 6, config['mealsaturation'])
    add_food("cheeseontoastitem", 6, config['mealsaturation'])
    add_food("tunapotatoitem", 7, config['mealsaturation'])
    add_food("chocolaterollitem", 3, config['mealsaturation'])
    add_food("jamrollitem", 4, config['mealsaturation'])
    add_food("coconutcreamitem", 2, config['mealsaturation'])
    add_food("crackeritem", 4, config['mealsaturation'])
    add_item("garammasalaitem")
    add_food("paneeritem", 1, config['mealsaturation'])    
    add_food("gravyitem", 3, config['mealsaturation'])
    add_food("mangochutneyitem", 4, config['mealsaturation'])
    add_food("marzipanitem", 3, config['mealsaturation'])
    add_food("paneertikkamasalaitem", 9, config['mealsaturation'])
    add_food("peaandhamsoupitem", 7, config['mealsaturation'])
    add_food("potatoandleeksoupitem", 7, config['mealsaturation'])
    add_food("yorkshirepuddingitem", 7, config['mealsaturation'])    

    add_item("sesameoilitem")    
    add_item("noodlesitem")
    add_food("chickenchowmeinitem", 8, config['mealsaturation'])
    add_food("kungpaochickenitem", 6, config['mealsaturation'])
    add_item("hoisinsauceitem")
    add_item("fivespiceitem")
    add_food("charsiuitem", 8, config['mealsaturation'])
    add_item("sweetandsoursauceitem")
    add_food("sweetandsourchickenitem", 8, config['mealsaturation'])
    add_food("baconandeggsitem", 4, config['mealsaturation'])
    add_food("biscuitsandgravyitem", 8, config['mealsaturation'])
    add_food("applefritteritem", 6, config['mealsaturation'])
    add_food("sweetteaitem", 4, config['mealsaturation'])
    add_food("creepercookieitem", 5, config['mealsaturation'])    

    add_food("honeybreaditem", 5, config['mealsaturation'])
    add_food("honeybunitem", 9, config['mealsaturation'])
    add_food("honeyglazedcarrotsitem", 6, config['mealsaturation'])
    add_food("honeyglazedhamitem", 5, config['mealsaturation'])
    add_food("honeysoyribsitem", 9, config['mealsaturation'])    
    
    add_food("chocovoxelsitem", 2, config['mealsaturation'])
    add_food("cinnamontoastitem", 7, config['mealsaturation'])    
    add_food("cornedbeefitem", 9, config['mealsaturation'])
    add_food("cottoncandyitem", 5, config['mealsaturation'])
    add_food("crackersitem", 6, config['mealsaturation'])
    add_food("creeperwingsitem", 6, config['mealsaturation'])
    add_food("dhalitem", 7, config['mealsaturation'])
    add_food("durianmilkshakeitem", 3, config['mealsaturation'])
    add_food("durianmuffinitem", 4, config['mealsaturation'])    
    add_item("hotsauceitem")
    add_food("hummusitem", 5, config['mealsaturation'])
    add_food("ironbrewitem", 9, config['mealsaturation'])
    add_food("lasagnaitem", 6, config['mealsaturation'])
    add_food("lemondrizzlecakeitem", 7, config['mealsaturation'])
    add_food("meatloafitem", 8, config['mealsaturation'])    
    add_food("mushroomlasagnaitem", 7, config['mealsaturation'])
    add_food("musselcookeditem", 2, config['mealsaturation'])
    add_food("netherwingsitem", 9, config['mealsaturation'])
    add_food("pizzasoupitem", 9, config['mealsaturation'])
    add_food("poutineitem", 7, config['mealsaturation'])
    add_food("salsaitem", 5, config['mealsaturation'])
    add_food("sardinesinhotsauceitem", 3, config['mealsaturation'])
    add_food("teriyakichickenitem", 8, config['mealsaturation'])    
    add_food("turkishdelightitem", 5, config['mealsaturation'])    

    add_food("greeneggsandhamitem", 5, config['mealsaturation'])    
    add_food("theatreboxitem", 7, config['mealsaturation'])
    add_food("cookiesandmilkitem", 2, config['mealsaturation'])
    add_food("crackersandcheeseitem", 8, config['mealsaturation'])
    add_food("chickendinneritem", 9, config['mealsaturation'])    

    add_food("corndogitem", 6, config['mealsaturation'])    
    add_food("hamandcheesesandwichitem", 7, config['mealsaturation'])    
    add_food("tunasaladitem", 9, config['mealsaturation'])
    add_food("gritsitem", 4, config['mealsaturation'])    

    add_food("buttercookieitem", 6, config['mealsaturation'])
    add_food("sugarcookieitem", 7, config['mealsaturation'])
    add_food("potatochipsitem", 3, config['mealsaturation'])
    add_food("bbqpotatochipsitem", 7, config['mealsaturation'])
    add_food("sourcreamandonionpotatochipsitem", 5, config['mealsaturation'])
    add_food("cheddarandsourcreampotatochipsitem", 6, config['mealsaturation'])
    add_food("tortillachipsitem", 5, config['mealsaturation'])    
    add_food("chipsanddipitem", 5, config['mealsaturation'])
    add_food("cheezepuffsitem", 4, config['mealsaturation'])
    add_food("surfandturfitem", 5, config['mealsaturation'])
    add_food("liverandonionsitem", 4, config['mealsaturation'])
    add_food("fortunecookieitem", 5, config['mealsaturation'])
    add_food("deviledeggitem", 7, config['mealsaturation'])
    add_food("mozzerellasticksitem", 6, config['mealsaturation'])    

    add_food("succotashitem", 5, config['mealsaturation'])    
    add_food("friedgreentomatoesitem", 5, config['mealsaturation'])    
    add_food("potatoesobrienitem", 4, config['mealsaturation'])
    add_food("tatertotsitem", 3, config['mealsaturation'])
    add_food("smoresitem", 9, config['mealsaturation'])    
    add_food("steakfajitaitem", 9, config['mealsaturation'])
    add_food("ramenitem", 4, config['mealsaturation'])
    add_food("misosoupitem", 3, config['mealsaturation'])
    add_food("onigiriitem", 3, config['mealsaturation'])
    add_food("grilledcheesevegemitetoastitem", 9, config['mealsaturation'])
    add_food("monsterfrieddumplingsitem", 6, config['mealsaturation'])    
    add_food("crispyricepuffcerealitem", 2, config['mealsaturation'])
    add_food("crispyricepuffbarsitem", 5, config['mealsaturation'])
    add_food("babaganoushitem", 5, config['mealsaturation'])
    add_food("berryvinaigrettesaladitem", 6, config['mealsaturation'])
    add_food("tomatoherbchickenitem", 4, config['mealsaturation'])
    add_food("pastagardeniaitem", 6, config['mealsaturation'])
    add_food("fiestacornsaladitem", 7, config['mealsaturation'])
    add_food("threebeansaladitem", 5, config['mealsaturation'])
    add_food("sweetandsourmeatballsitem", 6, config['mealsaturation'])
    add_food("pepperjellyitem", 2, config['mealsaturation'])
    add_food("pepperjellyandcrackersitem", 8, config['mealsaturation'])
    add_food("saltedcaramelitem", 2, config['mealsaturation'])
    add_food("spidereyepieitem", 6, config['mealsaturation'])
    add_food("cheesyshrimpquinoaitem", 9, config['mealsaturation'])
    add_food("bulgogiitem", 7, config['mealsaturation'])
    add_food("omuriceitem", 8, config['mealsaturation'])    
    add_food("pemmicanitem", 6, config['mealsaturation'])
    add_food("driedsoupitem", 3, config['mealsaturation'])
    add_food("crabkimbapitem", 6, config['mealsaturation'])
    add_food("froglegstirfryitem", 6, config['mealsaturation'])    
    add_food("haggisitem", 6, config['mealsaturation'])
    add_food("chickenkatsuitem", 6, config['mealsaturation'])
    add_food("chocolateorangeitem", 2, config['mealsaturation'])
    add_food("festivalbreaditem", 5, config['mealsaturation'])
    add_food("fruitcreamfestivalbreaditem", 7, config['mealsaturation'])
    add_food("phoitem", 6, config['mealsaturation'])
    add_food("bubbleteaitem", 4, config['mealsaturation'])
    add_food("duckrawitem", 1, config['mealsaturation'])
    add_food("duckcookeditem", 2, config['mealsaturation'])
    add_food("wontonsoupitem", 9, config['mealsaturation'])
    add_food("springrollitem", 7, config['mealsaturation'])
    add_food("meatystirfryitem", 6, config['mealsaturation'])
    add_food("potstickersitem", 7, config['mealsaturation'])
    add_food("orangeduckitem", 7, config['mealsaturation'])
    add_food("pekingduckitem", 7, config['mealsaturation'])
    add_food("stuffedduckitem", 7, config['mealsaturation'])
    add_item("rouxitem")    
    add_food("candiedpecansitem", 3, config['mealsaturation'])    

    add_food("stuffingitem", 8, config['mealsaturation'])
    add_food("greenbeancasseroleitem", 6, config['mealsaturation'])
    add_food("hamandpineapplepizzaitem", 9, config['mealsaturation'])    
    add_food("cobblestonecobbleritem", 6, config['mealsaturation'])
    add_food("crayfishsaladitem", 8, config['mealsaturation'])
    add_food("cevicheitem", 7, config['mealsaturation'])    
    add_food("bakedcactusitem", 1, config['mealsaturation'])
    add_food("garlicsteakitem", 6, config['mealsaturation'])
    add_food("mushroomsteakitem", 6, config['mealsaturation'])
    add_food("hotdishcasseroleitem", 9, config['mealsaturation'])
    add_food("sausagebeanmeltitem", 10, config['mealsaturation'])
    add_food("mettbrotchenitem", 8, config['mealsaturation'])    
    add_food("porkrindsitem", 4, config['mealsaturation'])
    add_food("cracklinsitem", 5, config['mealsaturation'])    
    add_food("chorusfruitsoupitem", 4, config['mealsaturation'])    
    add_food("akutuqitem", 5, config['mealsaturation'])
    add_food("cantonesegreensitem", 2, config['mealsaturation'])    
    add_food("earlgreyteaitem", 2, config['mealsaturation'])
    add_food("eggrollitem", 6, config['mealsaturation'])
    add_food("eggtartitem", 8, config['mealsaturation'])
    add_food("greenteaitem", 2, config['mealsaturation'])
    add_food("meesuaitem", 8, config['mealsaturation'])
    add_food("oystersauceitem", 4, config['mealsaturation'])
    add_food("squidinkspaghettiitem", 2, config['mealsaturation'])
    add_food("steaktartareitem", 6, config['mealsaturation'])
    add_food("szechuaneggplantitem", 9, config['mealsaturation'])    
    add_food("baconpancakesitem", 6, config['mealsaturation'])
    add_food("blackpaellaitem", 7, config['mealsaturation'])
    add_food("blazingsoupitem", 9, config['mealsaturation'])
    add_food("briochebunitem", 3, config['mealsaturation'])
    add_food("chickenpaellaitem", 8, config['mealsaturation'])
    add_food("escargotitem", 5, config['mealsaturation'])
    add_food("gourmetbeefpattyitem", 6, config['mealsaturation'])
    add_food("gourmetmuttonpattyitem", 6, config['mealsaturation'])
    add_food("gourmetporkpattyitem", 6, config['mealsaturation'])
    add_food("gourmetvenisonpattyitem", 6, config['mealsaturation'])
    add_food("guisoitem", 9, config['mealsaturation'])
    add_food("jelliedeelitem", 5, config['mealsaturation'])
    add_food("kalechipsitem", 2, config['mealsaturation'])
    add_food("padthaiitem", 8, config['mealsaturation'])
    add_food("peanutbutterbananasandwichitem", 5, config['mealsaturation'])
    add_food("peanutbuttercupitem", 3, config['mealsaturation'])
    add_food("pinkelitem", 4, config['mealsaturation'])
    add_food("pitepaltitem", 6, config['mealsaturation'])
    add_food("sauerbratenitem", 6, config['mealsaturation'])
    add_food("slimepieitem", 7, config['mealsaturation'])
    add_food("strawberryrhubarbpieitem", 6, config['mealsaturation'])
    add_food("tiropitaitem", 8, config['mealsaturation'])
    add_food("rosepetalteaitem", 2, config['mealsaturation'])    
    add_food("potatoskinsitem", 6, config['mealsaturation'])
    add_food("chilidonutitem", 6, config['mealsaturation'])
    add_food("bbqsauceitem", 1, config['mealsaturation'])
    add_food("vanillacupcakeitem", 8, config['mealsaturation'])
    add_food("chocolatecupcakeitem", 8, config['mealsaturation'])
    add_food("carrotcupcakeitem", 8, config['mealsaturation'])
    add_food("redvelvetcupcakeitem", 8, config['mealsaturation'])
    add_food("chilicupcakeitem", 8, config['mealsaturation'])
    add_food("peanutbuttercupcakeitem", 8, config['mealsaturation'])
    add_food("lemoncupcakeitem", 8, config['mealsaturation'])
    add_food("strawberrycupcakeitem", 8, config['mealsaturation'])
    add_food("mintcupcakeitem", 8, config['mealsaturation'])
    add_food("coffeecupcakeitem", 8, config['mealsaturation'])
    add_food("sprinklescupcakeitem", 8, config['mealsaturation'])
    add_food("caramelcupcakeitem", 8, config['mealsaturation'])
    add_food("cherryslushieitem", 3, config['mealsaturation'])
    add_food("pambitsboxitem", 8, config['mealsaturation'])
    add_food("stuffedchilipeppersitem", 7, config['mealsaturation'])
    add_food("slimegummiesitem", 2, config['mealsaturation'])
    add_food("chocolatepuddingitem", 3, config['mealsaturation'])
    add_food("bbqchickenpizzaitem", 9, config['mealsaturation'])
    add_food("quesadillaitem", 5, config['mealsaturation'])
    add_food("bibimbapitem", 8, config['mealsaturation'])
    add_food("shrimpcocktailitem", 5, config['mealsaturation'])
    add_food("nopalessaladitem", 6, config['mealsaturation'])
    add_item("meringueitem")
    add_food("applesnowitem", 4, config['mealsaturation'])
    add_food("bakedalaskaitem", 7, config['mealsaturation'])
    add_food("berrymeringuenestitem", 8, config['mealsaturation'])
    add_food("etonmessitem", 4, config['mealsaturation'])
    add_food("meringuebombeitem", 9, config['mealsaturation'])
    add_food("meringuebrownieitem", 5, config['mealsaturation'])
    add_food("meringuecookieitem", 6, config['mealsaturation'])
    add_food("meringuerouladeitem", 5, config['mealsaturation'])
    add_food("merveilleuxitem", 3, config['mealsaturation'])    
    add_food("bbqjackfruititem", 2, config['mealsaturation'])
    add_food("mushroomketchupomeletitem", 3, config['mealsaturation'])
    add_food("mushroomketchupitem", 1, config['mealsaturation'])
    add_food("lycheeteaitem", 3, config['mealsaturation'])
    add_food("baconwrappedchiliitem", 3, config['mealsaturation'])
    add_food("seedenergygelitem", 3, config['mealsaturation'])
    add_food("chickencordonbleuitem", 7, config['mealsaturation'])
    add_food("sundayhighteaitem", 9, config['mealsaturation'])
    add_food("cucumbersandwichitem", 8, config['mealsaturation'])
    add_food("dandelionsaladitem", 3, config['mealsaturation'])
    add_food("peanutsoupitem", 5, config['mealsaturation'])
    add_food("vanillaconchasbreaditem", 7, config['mealsaturation'])
    add_food("chocolatecoconutbaritem", 2, config['mealsaturation'])
    add_food("strawberrysouffleitem", 7, config['mealsaturation'])
    add_food("gyudonitem", 6, config['mealsaturation'])
    add_food("shrimptemperaitem", 4, config['mealsaturation'])
    add_food("imagawayakiitem", 5, config['mealsaturation'])
    add_food("mochicakeitem", 7, config['mealsaturation'])
    add_food("mochidessertitem", 6, config['mealsaturation'])
    add_food("taiyakiitem", 5, config['mealsaturation'])
    add_food("salmononigiriitem", 5, config['mealsaturation'])
    add_food("tunaonigiriitem", 5, config['mealsaturation'])
    add_food("friedbolognasandwichitem", 8, config['mealsaturation'])
    add_food("bolognasandwichitem", 9, config['mealsaturation'])
    add_food("ricepuddingitem", 5, config['mealsaturation'])
    add_food("musubiitem", 4, config['mealsaturation'])
    add_food("imitationcrabsticksitem", 6, config['mealsaturation'])
    add_food("misopasteitem", 1, config['mealsaturation'])
    add_food("dandelionteaitem", 3, config['mealsaturation'])
    add_food("gravlaxitem", 4, config['mealsaturation'])
    add_food("cheesedanishitem", 6, config['mealsaturation'])
    add_food("schnitzelitem", 6, config['mealsaturation'])
    add_food("bolognaitem", 2, config['mealsaturation'])
    add_food("raspberrymilkshakeitem", 5, config['mealsaturation'])
    add_food("pumpkinspicelatteitem", 8, config['mealsaturation'])
    add_food("rootbeerfloatitem", 6, config['mealsaturation'])
    add_food("hotcocoaitem", 5, config['mealsaturation'])
    add_food("cinnamonbreaditem", 6, config['mealsaturation'])
    add_food("cornchipsitem", 3, config['mealsaturation'])
    add_food("marshmellowchicksitem", 6, config['mealsaturation'])    
    add_food("pizzasliceitem", 2, config['mealsaturation'])    
    add_item("groundbeefitem")
    add_item("groundchickenitem")
    add_item("groundduckitem")
    add_item("groundfishitem")
    add_item("groundmuttonitem")
    add_item("groundporkitem")
    add_item("groundrabbititem")
    add_item("groundturkeyitem")
    add_item("groundvenisonitem")    
    add_food("rawtofeakitem", 1, config['snacksaturation'])
    add_food("rawtofaconitem", 1, config['snacksaturation'])
    add_food("rawtofishitem", 1, config['snacksaturation'])
    add_food("rawtofeegitem", 1, config['snacksaturation'])
    add_food("rawtofuttonitem", 1, config['snacksaturation'])
    add_food("rawtofickenitem", 1, config['snacksaturation'])
    add_food("rawtofabbititem", 1, config['snacksaturation'])
    add_food("rawtofurkeyitem", 1, config['snacksaturation'])
    add_food("rawtofenisonitem", 1, config['snacksaturation'])
    add_food("rawtofuduckitem", 1, config['snacksaturation'])    
    add_food("cookedtofeakitem", 2, config['mealsaturation'])
    add_food("cookedtofaconitem", 2, config['mealsaturation'])
    add_food("cookedtofishitem", 2, config['mealsaturation'])
    add_food("cookedtofeegitem", 2, config['mealsaturation'])
    add_food("cookedtofuttonitem", 2, config['mealsaturation'])
    add_food("cookedtofickenitem", 2, config['mealsaturation'])
    add_food("cookedtofabbititem", 2, config['mealsaturation'])
    add_food("cookedtofurkeyitem", 2, config['mealsaturation'])
    add_food("cookedtofenisonitem", 2, config['mealsaturation'])
    add_food("cookedtofuduckitem", 2, config['snacksaturation'])
    add_food("baconcheeseburgeritem", 10, config['mealsaturation'])
    add_food("deluxecheeseburgeritem", 10, config['mealsaturation'])
    add_food("beansontoastitem", 10, config['mealsaturation'])
    add_food("meatpieitem", 10, config['mealsaturation'])
    add_food("chikorollitem", 10, config['mealsaturation'])
    add_food("spinachpieitem", 10, config['mealsaturation'])
    add_food("coleslawburgeritem", 10, config['mealsaturation'])
    add_food("hotandsoursoupitem", 10, config['mealsaturation'])
    add_food("patreonpieitem", 10, config['mealsaturation'])
    add_food("chilidogitem", 10, config['mealsaturation'])
    add_food("tunafishsandwichitem", 10, config['mealsaturation'])
    add_food("clamchowderitem", 10, config['mealsaturation'])
    add_food("breakfastburritoitem", 10, config['mealsaturation'])
    add_food("chipsandsalsaitem", 10, config['mealsaturation'])
    add_food("crawfishetoufeeitem", 10, config['mealsaturation'])
    add_food("saucedlambkebabitem", 10, config['mealsaturation'])
    add_food("cantonesenoodlesitem", 10, config['mealsaturation'])
    add_food("dangoitem", 10, config['mealsaturation'])
    add_food("takoyakiitem", 10, config['mealsaturation'])
    add_food("groiledcheesesandwichitem", 10, config['mealsaturation'])
    add_food("cheesesteakitem", 10, config['mealsaturation'])
    add_food("swedishmeatballsitem", 10, config['mealsaturation'])
    add_food("buttertartitem", 10, config['mealsaturation'])    
    add_food("battenbergitem", 11, config['mealsaturation'])
    add_food("slawdogitem", 11, config['mealsaturation'])
    add_food("rivermudcakeitem", 11, config['mealsaturation'])
    add_food("fruitcakeitem", 11, config['mealsaturation'])
    add_food("springfieldcashewchickenitem", 11, config['mealsaturation'])
    add_food("enchiladaitem", 11, config['mealsaturation'])
    add_food("pizzaitem", 11, config['mealsaturation'])
    add_food("onionsoupitem", 11, config['mealsaturation'])
    add_food("baconmushroomburgeritem", 11, config['mealsaturation'])
    add_food("toadintheholeitem", 11, config['mealsaturation'])
    add_food("homestylelunchitem", 11, config['mealsaturation'])
    add_food("montecristosandwichitem", 11, config['mealsaturation'])
    add_food("mobsoupitem", 11, config['mealsaturation'])    
    add_food("randomtacoitem", 12, config['mealsaturation'])
    add_food("hamsweetpicklesandwichitem", 12, config['mealsaturation'])
    add_food("toastedwesternitem", 12, config['mealsaturation'])
    add_food("eggsbenedictitem", 12, config['mealsaturation'])
    add_food("glisteningsaladitem", 12, config['mealsaturation'])
    add_food("meatloafsandwichitem", 12, config['mealsaturation'])
    add_food("mashedpotatoeschickenbiscuititem", 12, config['mealsaturation'])    
    add_food("cassouletitem", 13, config['mealsaturation'])
    add_food("bratwurstitem", 13, config['mealsaturation'])
    add_food("chickenbiscuititem", 13, config['mealsaturation'])
    add_food("epicbltitem", 13, config['mealsaturation'])
    add_food("kohlundpinkelitem", 14, config['mealsaturation'])
    add_food("beetburgeritem", 13, config['mealsaturation'])
    add_food("anchovypepperonipizzaitem", 13, config['mealsaturation'])
    add_food("spaghettidinneritem", 13, config['mealsaturation'])
    add_food("gumboitem", 13, config['mealsaturation'])
    add_food("jambalayaitem", 13, config['mealsaturation'])    
    add_food("supremepizzaitem", 14, config['mealsaturation'])
    add_food("bbqplatteritem", 14, config['mealsaturation'])
    add_food("chickenandwafflesitem", 14, config['mealsaturation'])
    add_food("gourmetporkburgeritem", 14, config['mealsaturation'])
    add_food("bbqchickenbiscuititem", 14, config['mealsaturation'])    
    add_food("delightedmealitem", 15, config['mealsaturation'])
    add_food("heartybreakfastitem", 15, config['mealsaturation'])    
    add_food("mcpamitem", 16, config['mealsaturation'])
    add_food("deluxenachoesitem", 16, config['mealsaturation'])
    add_food("gourmetmuttonburgeritem", 16, config['mealsaturation'])
    add_food("netherstartoastitem", 16, config['mealsaturation'])
    add_food("paradiseburgeritem", 16, config['mealsaturation'])    
    add_food("chimichangaitem", 17, config['mealsaturation'])
    add_food("salisburysteakitem", 17, config['mealsaturation'])    
    add_food("ploughmanslunchitem", 18, config['mealsaturation'])
    add_food("cornedbeefhashitem", 18, config['mealsaturation'])
    add_food("bentoboxitem", 18, config['mealsaturation'])
    add_food("friedfeastitem", 18, config['mealsaturation'])    
    add_food("timpanoitem", 19, config['mealsaturation'])
    add_food("deluxechickencurryitem", 19, config['mealsaturation'])
    add_food("weekendpicnicitem", 19, config['mealsaturation'])
    add_food("gourmetbeefburgeritem", 19, config['mealsaturation'])    
    add_food("southernstylebreakfastitem", 20, config['mealsaturation'])    
    add_food("meatfeastpizzaitem", 24, config['mealsaturation'])
    add_food("thankfuldinneritem", 24, config['mealsaturation'])
    add_food("koreandinneritem", 24, config['mealsaturation'])
    add_food("gourmetvenisonburgeritem", 20, config['mealsaturation'])
    add_food("minerstewitem", 25, config['mealsaturation'])
    add_food("cornedbeefbreakfastitem", 26, config['mealsaturation'])


if __name__ == '__main__':
    if len(sys.argv) == 1:
        do_foods()
        export()
    if len(sys.argv) == 2:
        move_to_ingredients(sys.argv[1])

